### ISSUE TITLE
Missing countries: BV and HM

### ISSUE THREAD

**Issue by rkuebert** [umpirsky/country-list#52]
Hi,

while using https://github.com/umpirsky/country-list/blob/master/data/de_DE/country.txt , I noticed
the following two countries are missing:
Bouvet Island (BV)
Territory of Heard Island and McDonald Islands (HM)

Cheers

Roland

**Comment by umpirsky** [comment]
@rkuebert The source of country list is ICU database. So, this should be fixed in ICU.

**Comment by oliverpool** [comment]
They seem to be blacklisted by Symfony:

https://github.com/symfony/intl/blob/b79b8efab454ee088857df98467fd5b85f8f08b7/Data/Generator/RegionDataGenerator.php#L41

(this is not to reopen this issue, just for future visitors, to know where to better understand your statement ''So, this should be fixed in ICU.")

Cc: #70, #91

**Comment by umpirsky** [comment]
Oh, nice find. I didn't know they blacklist regions!
